const express=require('express')
require('dotenv').config()
const app=express()
const bodyParser=require('body-parser')
const {login,signup}=require('./controller/user')
const cors=require('cors')
app.use(cors())
app.use(express.json())
app.use(bodyParser.urlencoded({extended:true}))
app.get('/',(req,res)=>res.status(200).send("How can I help you"))
app.post('/signup',signup)
app.post('/login',login)
app.listen(5000,()=>console.log("app listen in 5000"))