const express=require('express')
require('dotenv').config()
const app=express()
const {login}=require('./controller/user')
app.get('/',(req,res)=>login(req,res))
app.listen(5000,()=>console.log("app listen in 5000"))