const express=require('express')
require('dotenv').config()
const app=express()
const http=require('http')
const server=http.createServer(app)
const socketio=require('socket.io')
const io=socketio(server,{cors:{origin:'*'}})
const bodyParser=require('body-parser')
const cors=require('cors')
const {login,signup,searchResult,followers}=require('./controller/user')
app.use(cors())
app.use(express.json())
app.use(bodyParser.urlencoded({extended:true}))
app.get('/',(req,res)=>res.status(200).send("How can I help you"))
app.post('/signup',signup)
app.post('/searchResult',searchResult)
app.post('/login',login)
io.on('connect',socket=>{
    socket.on('join',({me,name},callBack)=>{
        socket.join(me)
    })
    socket.on('follow',({me,you,name},callBack)=>{
        followers(me,you,name)
        io.to(me).emit('message',{me:me,you:you,name:name})
        io.to(you).emit('message',{me:you,you:me,name:name})
        callBack("done")
    })
})
server.listen(5000,()=>console.log("app listen in 5000"))